DO_DOUBLE_CHECK = False
INCLUDE_MODEL_IN_TAB = True
DEFAULT_STARTING_LOCATION = 'floor'
ASK_SCREWS_ON_TIGHT = False
ADJUSTMENT_INCLUDE_SECONDS = True
FINISH_AFTER_SUCCESSFULL_BIT = True
# Requires restart
INCLUDE_HOTKEYS = True
