DO_DOUBLE_CHECK = False
INCLUDE_MODEL_IN_TAB = True
DEFAULT_STARTING_LOCATION = 'floor'
ASK_SCREWS_ON_TIGHT = False
ADJUSTMENT_INCLUDE_SECONDS = True
FINISH_AFTER_SUCCESSFULL_BIT = True
ASSUME_SWAP_DOCK_ON_SUNKEN_CONTACT = False
SAVE_EVERY_STEP = False
# -1 or 0 or None to disable
SAVE_EVERY_MINUTES = 3

# Requires restart
INCLUDE_HOTKEYS = True
SHOW_HOTKEYS = False
